# Generated by Django 3.1.5 on 2021-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordsDefining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('pegi', models.CharField(max_length=3)),
                ('commentCount', models.CharField(max_length=11)),
                ('downloads', models.CharField(max_length=12)),
                ('ranking', models.CharField(max_length=4)),
            ],
        ),
    ]
